Replace browserify with webpack
- Requires bumping major version number as `spread(cytoscape, weaver)` can no longer be supported.
- Let webpack do umd lookups for dependencies.
- Drop support for cytoscape@2 as we no longer can use `cytoscape.Thread`.
- Tested in global case (demo) and commonjs app using webpack.
- Allow package-lock.json

Ref : Uncaught Error: Cannot find module 'weaverjs' #5